# Generated by Django 3.1.1 on 2025-10-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0002_auto_20251017_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
